# -*- coding: utf-8 -*-
"""Homework.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q0_dNcPpDtW3BbuX8BOJWkEcXxt-cqXD
"""

# HOMEWORK

#. Grade classifier write a program that takes a student's numerical grade as input and prints their corresponding letter grade according to the following scale
90 or above: A  80-89: B  70-79: C  60-69: D  below 60:F

marks = float(input("Enter your marks:"))

if marks>=90:
  print("Grade-A")
if marks>=80:
  print("Grade-B")
if marks>=70:
  print("Grade-C")
if marks>=60:
  print("Grade-D")
else:
  print("Grade-F")

#Even or Odd Write a program that takes an integer as input and determines whether it is even or odd.

Number = int(input("Enter any number"))

if Number%2==0:
  print ("its even")
else:
  print("its odd")

#Leap Year Checker Write a program that checks if a given year is a leap year. A leap year is either divisible by 4 but not by 100, or divisible by 400.

year = int(input("Enter any year:"))

if year%4==0:
  print("its a leap year")
if year%400==0:
  print("its also a leap year")
else:
  print("it is not a leap year")

#Positive, Negative, or Zero Write a program that takes a number as input and prints whether it is positive, negative, or zero.

number = int(input("enter any number:"))

if number>0:
  print("its positive")
if number<0:
  print("its negative")
else:
  print("its zero")

#Type Write a program that takes the lengths of three sides of a triangle as input and determines whether it's an equilateral, isosceles, or scalene triangle

a = int(input("enter first side:"))
b = int(input("enter second side:"))
c = int(input("enter third side:"))

if a==b and b==c and c==a:
  print("it's an equilateral triangle")
elif a==b and b==c and c!=a:
  print("it's an isosceles triangle")
else:
  print("it's an scalene triangle")



#Counting Odd Numbers Write a program that continuously takes input from the user until they enter a negative number. The program should then print the count of all the odd numbers entered.



#Print Even Numbers Write a program that prints all even numbers between 1 and 20



for i in range(1,21):
  if i%2==0:
    print (i)

#Calculate Factorial Write a program that calculates the factorial of a given positive integer.

number = int(input("Enter a positive integer: "))

import math
    if number < 0:
        print("Input must be a non-negative integer.")
    else:
        result = math.factorial(number)
        print(f"The factorial of {number} is {result}")

#Calculate Sum of Digits Write a program that calculates the sum of the digits of a given number.

def sumOfDigits(n):
    sum = 0
    while n != 0:

        # Extract the last digit
        last = n % 10

        # Add last digit to sum
        sum += last

        # Remove the last digit
        n //= 10
    return sum

sumOfDigits(2345)

# write a python programme to print square of even numbers and cube of odd numbers upto 20

for i in range (1,21):
  if i%2==0:
    print(i**2)
  else:
    print(i**3)

# Write a Python program to count number of vowels and consonants in a given sentence

def Check_Vow(string, vowels):

    # The term "casefold" has been used to refer to a method of ignoring cases.

    string = string.casefold()

    count = {}.fromkeys(vowels, 0)

    # To count the vowels

    for character in string:

        if character in count:

            count[character] += 1

    return count

Check_Vow("tarun","pubg")



#Homework question ; create a new list by squaring the elements

lst = [[[[[[[[4, 5, 6, 7, 8, 9, 8]]]]]]]]
A=[]
for i in lst[0][0][0][0][0][0][0]:
    i **= 2
    A.append(i)
    print(A)

#Write a function to find the sum of digits of a number.

def sumOfDigits(n):
    sum = 0
    while n != 0:

        # Extract the last digit
        last = n % 10

        # Add last digit to sum
        sum += last

        # Remove the last digit
        n //= 10
    return sum

sumOfDigits(7589)

