# -*- coding: utf-8 -*-
"""Matplotlib

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tvGrcNQ_i6PY7ZS_2soiLga8tXcKp7R1
"""

# Data Visualization - Matplotlib
# it is a library that helps us to visualize our data.
# helps to undertands dataset in a pictorial format.
# Extensively used in EDA, and to present Machine learning model results.
# it works best with numpy and pandas.

pip install matplotlib

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# line plot

x = np.arange(10)

x

y1 = x**2

y1

y2 = 2*x + 3

y2

plt.figure(figsize=(5,3))
plt.plot(x,y1)
plt.plot(x,y2)
plt.show()

themes = plt.style.available
print(themes)

plt.style.use("fivethirtyeight")

plt.figure(figsize=(5,3))
plt.plot(x,y1)
plt.plot(x,y2)
plt.show()

plt.figure(figsize=(5,3))
plt.plot(x,y1,color = "green",marker="o",markersize = 12 , label = "iPhone",linestyle =":")
plt.plot(x,y2,color = "pink",marker = "*",markersize = 20,label ="Android",linestyle = "-.")
plt.legend()
plt.xlabel("Time")
plt.ylabel("Sales")
plt.title("Sales of TV over period of time ")
plt.show()

